# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Notes
email: info@weibeld.net
baseurl: "/mynotes"  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%-d %b %Y"


# Build settings
markdown: kramdown

# Default settings
defaults:
  - values:
      layout: page

# Include directories in Jekyll processing
include:
  - _pages

# Collections
#
# With Jekyll version 3.7.0 all the collection directories can be gathered in a
# single top-level directory. This directory can be specified in _config.yml
# by "collections_dir: my_collections" (https://jekyllrb.com/docs/collections/).
#
# However, this can only be used when GitHub Pages updates to Jekyll v3.7.0.
# Check currently used Jekyll version here: https://pages.github.com/versions/
collections:
  android:
    output: true
    title: Android
    #permalink: /categories/:collection/:path/
    image: /assets/icons/android.png
    description: >
      Notes about the Android SDK and other Android-related topics. And some more information to make the text longer.
  google:
    output: true
    title: Google
    #permalink: /categories/:collection/:path/
    image: /assets/icons/google.png
    description: >
      Google products, such as Google Photos, Google Fonts, etc.
  terminals-and-shells:
    output: true
    title: Terminals & Shells
    image: /assets/icons/terminals-and-shells.png
    description: >
      Notes about different terminals and shells, including iTerm and Bash.
  markdown:
    output: true
    title: Markdown
    image: /assets/icons/markdown.png
    description: >
      Various notes about the Markdown markup language, Markdown processors, as well as the R Markdown environment.
  pdf:
    output: true
    title: PDF
    image: /assets/icons/pdf.png
    description: >
      Notes about editing PDF files with command-line tools.
  aws:
    output: true
    title: Amazon Web Services
    image: /assets/icons/aws.png
    description: >
      Some notes about specific Amazon Web Services (AWS) products, in particular Amazon S3.
  vim:
    output: true
    title: Vim
    image: /assets/icons/vim.png
    description: >
      The amazing vim editor, successor of vi, visual mode of ex, successor of ed, better version of qed.
  latex:
    output: true
    title: LaTeX
    image: /assets/icons/latex.png
    description: >
      A bunch of how to's and code snippets for LaTeX and related tools, such as BibTeX and BibDesk.
  categories:
    output: true
    permalink: /:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
