# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Notes
email: info@weibeld.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/mynotes" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: weibeld
date_format: "%-d %b %Y'"


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Further settings

# Process the files in the _pages folder
include:
  - _pages

collections:
  android:
    output: true
    title: Android
    #permalink: /categories/:collection/:path/
    image: /assets/icons/android.png
    description: >
      Notes about the Android SDK and other Android-related topics. And some more information to make the text longer.
  google:
    output: true
    title: Google
    #permalink: /categories/:collection/:path/
    image: /assets/icons/google.png
    description: >
      Google products, such as Google Photos, Google Fonts, etc.
  terminals-and-shells:
    output: true
    title: Terminals & Shells
    image: /assets/icons/terminals-and-shells.png
    description: >
      Notes about different terminals and shells, including iTerm and Bash.
  markdown:
    output: true
    title: Markdown
    image: /assets/icons/markdown.png
    description: >
      Various notes about the Markdown markup language, Markdown processors, as well as the R Markdown environment.
  pdf:
    output: true
    title: PDF
    image: /assets/icons/pdf.png
    description: >
      Notes about editing PDF files with command-line tools.
  categories:
    output: true
    permalink: /:path/

defaults:
  - values:
      layout: page
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
